---
- stat: path=~/xcode.keychain
  sudo: no
  register: keychain

- name: Create xcode.keychain
  sudo: no
  shell: security -v create-keychain -p "{{osx_keychain_password}}" ~/xcode.keychain
  no_log: yes
  ignore_errors: yes

- name: Create unlock_keychain.sh
  template: src=unlock_keychain.sh dest=~/unlock_keychain.sh mode=0700
  sudo: no

- name: Set keychain settings
  shell: ~/unlock_keychain.sh && security -v set-keychain-settings ~/xcode.keychain
  sudo: no

- name: Set default keychain
  shell: ~/unlock_keychain.sh && security -v default-keychain -s ~/xcode.keychain
  sudo: no

- name: Copy codesigning key/certificate
  copy: src=julia-osx-codesign.p12 dest=~/julia-osx-codesign.p12
  sudo: no

- name: Import codesigning key/certificate
  sudo: no
  shell: ~/unlock_keychain.sh && security -v import ~/julia-osx-codesign.p12 -k ~/xcode.keychain -T /usr/bin/codesign -P "{{osx_codesign_key_password}}"
  ignore_errors: yes

- name: Cleanup key/certificate
  file: path=~/julia-osx-codesign.p12 state=absent