---
- name: Make space for buildbot-worker environment
  file: dest=~/buildbot mode=755 state=directory
  sudo: no

- name: Check if buildbot-worker is already installed
  sudo: no
  stat: path=~/buildbot/sandbox/bin/buildbot-worker
  register: worker

- name: Stop buildbot if it's already running
  shell: chdir=~/buildbot sandbox/bin/buildbot-worker stop worker
  when: worker.stat.exists == True
  ignore_errors: yes
  sudo: no

- name: Install virtualenv to ~/buildbot/sandbox
  shell: chdir=~/buildbot virtualenv --no-site-packages sandbox
  sudo: no

- name: Install buildbot-worker to ~/buildbot/sandbox
  pip: name=buildbot-worker==0.9rc4 virtualenv=~/buildbot/sandbox state=latest
  sudo: no

- name: Configure buildbot-worker
  shell: chdir=~/buildbot sandbox/bin/buildbot-worker create-worker --keepalive=100 --umask 022 worker {{buildbot_server}}:{{buildbot_port}} {{hostname.stdout}} {{buildbot_password}}
  sudo: no

- name: Set buildbot-worker admin info
  copy: dest=~/buildbot/worker/info/admin content="Elliot Saba <staticfloat@gmail.com>"
  sudo: no

- name: Set buildbot-worker host info
  copy: dest=~/buildbot/worker/info/host content="Julia {{hostname.stdout}} buildbot-worker"
  sudo: no
