---
- include: packages_apt.yml
  when: ansible_os_family == "Debian"

- include: packages_yum.yml
  when: ansible_os_family == "RedHat"

- include: packages_brew.yml
  when: ansible_os_family == "Darwin"
- include: codesign_osx.yml
  when: ansible_os_family == "Darwin"

- include: packages_cygwin.yml
  when: ansible_os_family == "NA"

- include: misc.yml
- include: install_buildbot.yml