---
# Install Homebrew, don't let it ask questions
- name: Install Homebrew
  sudo: yes
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null

- name: Update homebrew and upgrade all installed software
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install necessary buildslave packages
  homebrew: name={{item}} state=latest
  with_items:
    - gcc
    - git
    - python
    - cmake
    - curl
    - ccache

    # Needed because they're awesome
    - htop
    - tmux
    - nano

- name: Install virtualenv
  pip: name=virtualenv state=latest