---
- name: Update yum cache and upgrade all installed software
  sudo: yes
  yum: update_cache=yes name=* state=latest
  # ansible 1.9.2 sucks!
  ignore_errors: yes

- name: Install necessary buildslave packages
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    # Needed for building Julia and co.
    - curl
    - git
    - gcc
    - gcc-c++
    - gcc-gfortran
    - m4
    - kernel-devel
    - python
    - python-devel
    - ccache
    - rpmdevtools
    - openssl-devel

    # Needed because they're awesome
    - htop
    - tmux
    - nano
    - net-tools

- name: Install python26 and cmake28 on ancient systems
  yum: name={{item}} state=latest
  with_items:
    - python26-devel
    - python-ssl
    - cmake28
  when: ansible_distribution_major_version == "5"

- name: Download python26-distribute on ancient systems
  get_url: url=https://cache.e.ip.saba.us/http://ftp.is.co.za/mirror/fedora.redhat.com/epel/5/{{ansible_architecture}}/python26-distribute-0.6.10-4.el5.noarch.rpm dest=/tmp/
  when: ansible_distribution_major_version == "5"

- name: Install python26-distribute on ancient systems
  command: rpm -iv /tmp/python26-distribute-0.6.10-4.el5.noarch.rpm
  when: ansible_distribution_major_version == "5"
  ignore_errors: yes

- name: Install pip on ancient systems
  command: easy_install-2.6 pip
  when: ansible_distribution_major_version == "5"

- name: Cleanup python26-distribute on ancient systems
  file: path=/tmp/python26-distribute-0.6.10-4.el5.noarch.rpm state=absent

- name: Install packages on newer systems
  yum: name={{item}} state=latest
  with_items:
    - python-pip
    - copr-cli
    - cmake
  when: ansible_distribution_major_version != "5"

- name: Install virtualenv
  pip: name=virtualenv state=latest
  sudo: yes
