---
- name: Update homebrew and upgrade all installed software
  sudo: no
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install necessary buildslave packages
  sudo: no
  homebrew: name={{item}} state=latest
  with_items:
    - gcc
    - git
    - python
    - cmake
    - curl
    - ccache
    - platypus

    # Needed because they're awesome
    - htop
    - tmux

- name: Install virtualenv
  sudo: no
  pip: name=virtualenv state=latest