---
- name: Update yum cache and upgrade all installed software
  become: yes
  yum: update_cache=yes name=* state=latest
  # ansible 1.9.2 sucks!
  ignore_errors: yes

- name: Install necessary buildslave packages
  yum: name={{ item }} state=present
  become: yes
  ignore_errors: yes
  with_items:
    # Needed for building Julia and co.
    - curl
    - git
    - gcc
    - gcc-c++
    - gcc-gfortran
    - m4
    - kernel-devel
    - python
    - python-devel
    - rpmdevtools
    - openssl
    - openssl-devel
    - libedit-devel

    # Needed because they're awesome
    - htop
    - tmux
    - nano
    - net-tools

- name: Install cmake28 on ancient systems
  yum: name={{item}} state=latest
  with_items:
    - python-ssl
    - cmake28
  when: ansible_distribution_major_version == "5"

- name: Install packages on newer systems
  yum: name={{item}} state=latest
  ignore_errors: yes
  with_items:
    - python-pip
    - copr-cli
    - cmake
  when: ansible_distribution_major_version != "5"

- name: Install virtualenv
  pip: name=virtualenv state=latest
  become: yes
